### PR TITLE
Multi-metadata support

### PR DESCRIPTION
**Pull request by iprotsyuk**
- Reduced minimal metadata to exclude IMS-specific fields
- Put IMS-specific fields to a separate JSON schema as an extension of the minimal one
- Added another JSON schema with LC-MS specific fields
- Added `Adducts` field to `Metaspace_options`

### CODE REVIEW

**Comment by intsco** [comment]
@iprotsyuk merged into lcms-support

**Comment by iprotsyuk** [comment]
@intsco can you pull my last commit to `lcms-support` as well?

**Comment by intsco** [comment]
@iprotsyuk sure I will, meanwhile could you send a new PR into lcms-support branch?

**Comment by iprotsyuk** [comment]
ok, will do

**Pull request closed without merging**
